# Generated by Django 5.2.1 on 2025-05-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boundary_polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon data for property boundaries', null=True),
        ),
    ]
