# Generated by Django 5.2.1 on 2025-06-04 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_publication_status_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
