# Generated by Django 5.2.1 on 2025-06-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_tour_description_tour_name_tour_package_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('both', 'Both')], default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rental_terms',
            field=models.TextField(blank=True),
        ),
    ]
