# Generated by Django 5.2.1 on 2025-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_recordingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('active', 'Active'), ('error', 'Error')], default='active', max_length=20),
        ),
    ]


