# Generated by Django 4.2.23 on 2025-07-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('2.0-flash', '2.0 Flash'), ('2.5-flash', '2.5 Flash'), ('2.5-pro', '2.5 Pro')], max_length=50, unique=True)),
                ('price_per_1k_tokens_input', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('price_per_1k_tokens_output', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('system_prompt', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_input', models.PositiveIntegerField()),
                ('tokens_output', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=6, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_management.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
