# Generated by Django 5.2.1 on 2025-05-26 20:37

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='boundary_polygon',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon data for property boundaries', null=True, validators=[properties.models.validate_boundary_polygon]),
        ),
    ]
