# Generated by Django 4.2.23 on 2025-08-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_btcpay_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BTCPayEvent',
        ),
        migrations.DeleteModel(
            name='BTCPayInvoice',
        ),
    ]
