# Generated by Django 4.2.23 on 2025-07-08 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_management', '0002_update_ai_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiusagelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='samconfiguration',
            options={'verbose_name': 'Configuración de Sam', 'verbose_name_plural': 'Configuraciones de Sam'},
        ),
        migrations.RemoveIndex(
            model_name='aiusagelog',
            name='ai_manageme_timesta_d1a8c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiusagelog',
            name='ai_manageme_model_u_99c9b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiusagelog',
            name='ai_manageme_user_id_c1b5d3_idx',
        ),
        migrations.RemoveField(
            model_name='samconfiguration',
            name='max_conversation_history',
        ),
        migrations.AddField(
            model_name='samconfiguration',
            name='max_history_messages',
            field=models.PositiveSmallIntegerField(default=10, help_text='Número máximo de mensajes (usuario + asistente) a retener en el historial de la conversación. Un número par es recomendado.'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='api_name',
            field=models.CharField(help_text='Nombre del modelo usado en la API de Google (ej. gemini-1.5-pro-latest)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Si está activo, puede ser seleccionado en la configuración.'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='max_tokens',
            field=models.PositiveIntegerField(default=8192, help_text='Máximo de tokens que el modelo puede procesar en una sola llamada.'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo para el modelo (ej. Gemini 2.5 Pro)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='price_per_1k_tokens_input',
            field=models.DecimalField(decimal_places=6, help_text='Costo por 1000 tokens de entrada (prompt)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='price_per_1k_tokens_output',
            field=models.DecimalField(decimal_places=6, help_text='Costo por 1000 tokens de salida (respuesta)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='supports_thinking',
            field=models.BooleanField(default=False, help_text='Indica si el modelo soporta la función de "pensamiento" o tool-calling.'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='Instrucción de sistema por defecto para este modelo.'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='model_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai_management.aimodel'),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='request_type',
            field=models.CharField(default='chat', help_text='Tipo de solicitud (ej. chat, search, summarization)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='response_time_ms',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo de respuesta en milisegundos.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aiusagelog',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='samconfiguration',
            name='current_model',
            field=models.ForeignKey(blank=True, help_text='El modelo de IA que Sam usará para responder.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_management.aimodel'),
        ),
        migrations.AlterField(
            model_name='samconfiguration',
            name='custom_instructions',
            field=models.TextField(blank=True, default='Eres Sam, el asistente de IA de SkyTerra. Ayudas a los usuarios a encontrar propiedades y responder preguntas sobre bienes raíces.', help_text='Instrucciones personalizadas para el asistente de IA.'),
        ),
        migrations.AlterField(
            model_name='samconfiguration',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Activa o desactiva globalmente el asistente Sam.'),
        ),
        migrations.AlterField(
            model_name='samconfiguration',
            name='response_temperature',
            field=models.FloatField(default=0.7, help_text='Controla la aleatoriedad de la respuesta. Valores más altos (ej. 1.0) son más creativos, valores más bajos (ej. 0.2) son más deterministas.'),
        ),
        migrations.AlterField(
            model_name='samconfiguration',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sam_configs_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
