# Generated by Django 4.2.23 on 2025-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_management', '0003_alter_aiusagelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='api_name',
            field=models.CharField(help_text='Nombre del modelo usado en la API de Google (ej. gemini-2.5-pro)', max_length=100, unique=True),
        ),
    ]
