# Generated by Django 5.2.1 on 2025-06-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_publication_status_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="publication_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Estado de publicación de la propiedad",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
