# Generated by Django 5.2.1 on 2025-06-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_tour_tour_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='package_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='type',
            field=models.CharField(choices=[('360', '360°'), ('video', 'Video'), ('package', 'Package'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
