# Generated by Django 4.2.23 on 2025-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_comparisonsession_favorite_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='access',
            field=models.CharField(blank=True, choices=[('paved', 'Pavimentado'), ('unpaved', 'No pavimentado')], default='paved', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('clear', 'Saneado'), ('mortgaged', 'Con hipoteca')], default='clear', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='terrain',
            field=models.CharField(blank=True, choices=[('flat', 'Plano'), ('hills', 'Colinas'), ('mountains', 'Montañoso'), ('mixed', 'Mixto')], default='flat', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities',
            field=models.JSONField(blank=True, default=list, help_text="Lista de servicios disponibles (ej. ['water', 'electricity'])"),
        ),
    ]
