# Generated by Django 4.2.23 on 2025-08-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_access_property_legal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='plusvalia_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Métrica que refleja el potencial de plusvalía (0-100). Visible para suscriptores Pro.', max_digits=5, null=True),
        ),
    ]
