# Generated by Django 4.2.23 on 2025-10-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0019_job_listingplan_property_access_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="address_country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="address_line1",
            field=models.CharField(
                blank=True,
                help_text="Dirección o punto de encuentro principal para la grabación.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="address_line2",
            field=models.CharField(
                blank=True,
                help_text="Información adicional de la dirección (interior, lote, etc.).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="address_postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="property",
            name="address_region",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                help_text="Correo directo del vendedor o encargado.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre de contacto principal para coordinar la visita del piloto.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Teléfono del vendedor o encargado disponible para los pilotos.",
                max_length=32,
            ),
        ),
    ]
