# Generated by Django 4.2.23 on 2025-10-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0020_property_address_city_property_address_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pilotprofile",
            name="base_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="coverage_radius_km",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="drone_model",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="experience_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="portfolio_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="pilotprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="pilotdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("id", "Identificación"),
                    ("license", "Licencia de piloto"),
                    ("drone_registration", "Registro de dron"),
                    ("insurance", "Seguro"),
                    ("background_check", "Certificado de antecedentes"),
                    ("other", "Otro"),
                ],
                max_length=50,
            ),
        ),
    ]
