# Generated by Django 4.2.23 on 2025-08-08 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_bitcoin_coinbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
